# Generated by Django 5.2.10 on 2026-01-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.TextField(),
        ),
    ]
